import { describe, expect, it, vi } from 'vitest'
import { render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import EbookLibrary from './EbookLibrary'
import { admin, ebook, mockEbookApi } from '../../test/ebookFixtures'

describe('ebook management library', () => {
  it('renders loading, metadata, size, status, and publication controls', async () => {
    const api = mockEbookApi()
    render(<EbookLibrary api={api} user={admin} onSignOut={vi.fn()} />)
    expect(screen.getByRole('status', { name: 'Loading ebooks' })).toBeVisible()
    expect(await screen.findByRole('heading', { name: ebook.title })).toBeVisible()
    expect(screen.getByText('1 MB')).toBeVisible()
    expect(screen.getByText('READY')).toBeVisible()
    expect(screen.getByRole('button', { name: 'Publish', exact: true })).toBeEnabled()
  })
  it('searches and filters using server pagination', async () => {
    const api = mockEbookApi()
    api.list.mockResolvedValue({ data: [ebook], pagination: { page: 1, limit: 9, total: 20, pages: 3 } })
    const user = userEvent.setup()
    render(<EbookLibrary api={api} user={admin} onSignOut={vi.fn()} />)
    await screen.findByRole('heading', { name: ebook.title })
    await user.type(screen.getByLabelText('Search ebooks'), 'Wellbeing')
    await user.click(screen.getByRole('button', { name: 'Search', exact: true }))
    await waitFor(() => expect(api.list).toHaveBeenLastCalledWith(expect.objectContaining({ q: 'Wellbeing', page: 1 }), expect.any(AbortSignal)))
    await user.selectOptions(screen.getByLabelText('Status'), 'PUBLISHED')
    await waitFor(() => expect(api.list).toHaveBeenLastCalledWith(expect.objectContaining({ status: 'PUBLISHED', page: 1 }), expect.any(AbortSignal)))
    await user.click(screen.getByRole('button', { name: 'Next', exact: true }))
    await waitFor(() => expect(api.list).toHaveBeenLastCalledWith(expect.objectContaining({ page: 2 }), expect.any(AbortSignal)))
  })
  it('renders the empty library and opens the create form', async () => {
    const api = mockEbookApi()
    api.list.mockResolvedValue({ data: [], pagination: { page: 1, limit: 9, total: 0, pages: 0 } })
    const user = userEvent.setup()
    const { container } = render(<main className="app"><EbookLibrary api={api} user={admin} onSignOut={vi.fn()} /></main>)
    expect(await screen.findByRole('heading', { name: 'Your library starts here' })).toBeVisible()
    await user.click(screen.getByRole('button', { name: 'Create first ebook' }))
    expect(screen.getByRole('dialog', { name: 'Create Ebook' })).toBeVisible()
    expect(container.querySelector('[role="dialog"]')).toBeNull()
    expect(screen.getByRole('dialog', { name: 'Create Ebook' }).parentElement?.parentElement).toBe(document.body)
    expect(screen.getByRole('textbox', { name: 'Title' })).toHaveFocus()
    expect(screen.getByLabelText('Choose PDF')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Close', exact: true }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Create first ebook' })).toHaveFocus()
  })
  it('provides a safe error and retries a failed list request', async () => {
    const api = mockEbookApi()
    api.list.mockRejectedValueOnce(new Error('SECRET backend stack'))
    const user = userEvent.setup()
    render(<EbookLibrary api={api} user={admin} onSignOut={vi.fn()} />)
    expect(await screen.findByRole('alert')).toHaveTextContent('Unable to load ebooks')
    expect(screen.queryByText(/SECRET/)).not.toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Try again' }))
    expect(await screen.findByRole('heading', { name: ebook.title })).toBeVisible()
  })
  it('publishes, unpublishes, and confirms deletion', async () => {
    const api = mockEbookApi()
    const user = userEvent.setup()
    render(<EbookLibrary api={api} user={admin} onSignOut={vi.fn()} />)
    await screen.findByRole('heading', { name: ebook.title })
    await user.click(screen.getByRole('button', { name: 'Publish', exact: true }))
    expect(api.publish).toHaveBeenCalledWith(ebook._id, true)
    api.list.mockResolvedValue({ data: [{ ...ebook, isPublished: true, status: 'PUBLISHED' }], pagination: { page: 1, limit: 9, total: 1, pages: 1 } })
    await user.click(screen.getByRole('button', { name: 'Refresh' }))
    await user.click(await screen.findByRole('button', { name: 'Unpublish' }))
    expect(api.publish).toHaveBeenCalledWith(ebook._id, false)
    await user.click(await screen.findByRole('button', { name: 'Delete', exact: true }))
    expect(api.remove).not.toHaveBeenCalled()
    const dialog = screen.getByRole('dialog', { name: 'Delete ebook?' })
    await user.click(within(dialog).getByRole('button', { name: 'Delete ebook', exact: true }))
    expect(api.remove).toHaveBeenCalledWith(ebook._id)
  })
  it('does not let draft ebooks publish', async () => {
    const api = mockEbookApi()
    api.list.mockResolvedValue({ data: [{ ...ebook, status: 'DRAFT', pdfSizeBytes: null }], pagination: { page: 1, limit: 9, total: 1, pages: 1 } })
    render(<EbookLibrary api={api} user={admin} onSignOut={vi.fn()} />)
    await screen.findByRole('heading', { name: ebook.title })
    expect(screen.getByRole('button', { name: 'Publish', exact: true })).toBeDisabled()
  })
})
